"""Generate the launcher-icon prototypes in docs/icons/ (see docs/icon-options.md).

Each foreground is one flat white shape with real cut-outs (no overlapping colours), so the same
drawable works as the adaptive icon's monochrome layer. Coordinates are on the 108dp canvas and
stay inside the 66dp safe zone.

    python3 -m venv /tmp/venv && /tmp/venv/bin/pip install shapely
    /tmp/venv/bin/python docs/icons/generate.py    # also needs rsvg-convert (librsvg)

Option 1 is the app's icon: after changing it, copy option1-qr-bolt/ic_launcher_foreground.xml
to app/src/main/res/drawable/ and its colour to app/src/main/res/values/colors.xml.
"""
import math
import subprocess
from pathlib import Path

from shapely import affinity
from shapely.geometry import LineString, Point, Polygon, box
from shapely.ops import unary_union

C = 54.0  # canvas centre
SAFE_R = 33.0
OUT = Path(__file__).parent


def rrect(x0, y0, x1, y1, r):
    return box(x0 + r, y0 + r, x1 - r, y1 - r).buffer(r, quad_segs=16)


def stroke(coords, w):
    return LineString(coords).buffer(w / 2, cap_style="flat", join_style="mitre", mitre_limit=4)


def arc(cx, cy, r, a0, a1, n=48):
    return [(cx + r * math.cos(math.radians(a0 + (a1 - a0) * i / n)),
             cy + r * math.sin(math.radians(a0 + (a1 - a0) * i / n))) for i in range(n + 1)]


def parts(geom):
    return list(getattr(geom, "geoms", [geom]))


def max_r(geom):
    return max(Point(C, C).distance(Point(p)) for g in parts(geom) for p in g.exterior.coords)


def path_data(geom):
    def ring(coords):
        pts = [f"{x:.2f},{y:.2f}".replace(".00", "") for x, y in list(coords)[:-1]]
        return "M" + pts[0] + " L" + " ".join(pts[1:]) + " Z"

    out = []
    for p in parts(geom.simplify(0.02, preserve_topology=True)):
        out.append(ring(p.exterior.coords))
        out += [ring(i.coords) for i in p.interiors]
    return " ".join(out)


def qr_bolt():
    """A QR finder pattern whose centre is a lightning bolt that breaks through the ring."""
    size = 46.0  # 7 modules
    m = size / 7
    x0 = C - size / 2
    ring = rrect(x0, x0, x0 + size, x0 + size, 7).difference(
        rrect(x0 + m, x0 + m, x0 + size - m, x0 + size - m, 3.5))

    bolt = Polygon([(57, 21), (71, 21), (61, 47), (72, 47), (46, 88), (52, 58), (38, 58)])
    bolt = affinity.translate(bolt, C - bolt.centroid.x, C - bolt.centroid.y)
    bolt = affinity.scale(bolt, 0.78, 0.85, origin=(C, C))
    bolt = affinity.scale(bolt, 32 / max_r(bolt), 32 / max_r(bolt), origin=(C, C))
    b = list(bolt.exterior.coords)

    def extend(p, q, y):  # point on line p->q carried to height y
        return (p[0] + (q[0] - p[0]) * (y - p[1]) / (q[1] - p[1]), y)

    # Cut the ring along the bolt's top edges carried past the ring, so the ring ends are straight.
    top = Polygon([b[0], b[1], extend(b[2], b[1], 24), extend(b[5], b[0], 24)])
    gap = 2.8
    ring = ring.difference(bolt.buffer(gap).union(top.buffer(gap, join_style="mitre")))
    ring = ring.buffer(-1.2).buffer(1.2)  # drop slivers
    return ring.union(bolt)


def bookmark_rupee():
    """A bookmark ribbon with a bold rupee sign cut out of it."""
    x0, x1, y0, y1, notch = 36, 72, 25, 81, 70
    ribbon = Polygon([(x0, y0), (x1, y0), (x1, y1), (C, notch), (x0, y1)])
    ribbon = ribbon.difference(box(x0, y0, x1, y0 + 6)).union(rrect(x0, y0, x1, y0 + 12, 5))

    w = 4.6                        # stroke width
    rx0, rx1 = 44.5, 63.5          # rupee left and right
    t1, t2 = 36.5, 44.5            # centre lines of the two bars
    r = t2 - t1 + 1.5              # bowl radius
    cx, cy = 50.0, t1 + r
    rupee = unary_union([
        stroke([(rx0, t1), (rx1, t1)], w),
        stroke([(rx0, t2), (rx1, t2)], w),
        stroke([(rx0, t1), (cx, t1)] + arc(cx, cy, r, -90, 90)[1:] + [(cx - 3, cy + r)], w),
        stroke([(cx - 3.2, cy + r - w / 2 + 0.3), (rx1 - 1.5, 72)], w * 1.1),
    ]).intersection(box(0, 0, 108, 73.2))
    return ribbon.difference(rupee)


VECTOR = """<?xml version="1.0" encoding="utf-8"?>
<!-- {comment} Generated by docs/icons/generate.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FFFFFF"
        android:fillType="evenOdd"
        android:pathData="{path}" />
</vector>
"""

COLORS = """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{color}</color>
</resources>
"""

def play_icon(geom, color, out):
    """Google Play store icon: 512x512 32-bit PNG, full-bleed square (Play applies the rounded
    mask and shadow itself). Framed on the 72dp a launcher shows, so it matches the home screen."""
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="18 18 72 72">'
           f'<rect width="108" height="108" fill="{color}"/>'
           f'<path d="{path_data(geom)}" fill="#FFFFFF" fill-rule="evenodd"/></svg>')
    png = subprocess.run(["rsvg-convert", "-w", "512", "-h", "512"], input=svg.encode(),
                         capture_output=True, check=True).stdout
    # rsvg drops the alpha channel of an opaque image; Play wants 32-bit (RGBA).
    subprocess.run(["convert", "png:-", f"PNG32:{out}"], input=png, check=True)


OPTIONS = [
    ("option1-qr-bolt", qr_bolt, "#0F5F5C",
     "QR finder pattern with a lightning bolt cut through it (option 1)."),
    ("option2-bookmark-rupee", bookmark_rupee, "#2B3A8C",
     "Bookmark ribbon with a rupee sign cut out (option 2)."),
]

if __name__ == "__main__":
    for name, shape, color, comment in OPTIONS:
        geom = shape()
        r = max_r(geom)
        assert r <= SAFE_R, f"{name} leaves the safe zone (r={r:.1f})"
        d = OUT / name
        d.mkdir(exist_ok=True)
        (d / "ic_launcher_foreground.xml").write_text(VECTOR.format(comment=comment, path=path_data(geom)))
        (d / "colors.xml").write_text(COLORS.format(color=color))
        play_icon(geom, color, d / "ic_launcher-playstore.png")
        print(f"{name}: r={r:.1f}, {len(path_data(geom))} chars of path data")
